Improved publish/do-publish command.

diff --git a/publish/do-publish b/publish/do-publish
--- a/publish/do-publish
+++ b/publish/do-publish
@@ -1,26 +1,28 @@
 #!/usr/bin/env bash
 
 if [ $# -eq 0 ]; then
-	echo "Missing file/s to publish"
-	exit 1
+  echo "Missing file/s to publish"
+  exit 1
 fi
 
 if [ "$PUBLISH_DIR" == "" ]; then
-	echo "Missing PUBLISH_DIR"
-	exit 1
+  echo "Missing PUBLISH_DIR"
+  exit 1
 fi
 
 if [ ! -d "$PUBLISH_DIR" ]; then
-	echo "Not a folder: $PUBLISH_DIR"
-	exit 1
+  echo "Not a folder: $PUBLISH_DIR"
+  exit 1
 fi
 
 for file in "$@"
 do
-	if [ ! -f "$file" ]; then
-		echo "Skipping $file"
-		continue
-	fi
-	cp "$file" "$PUBLISH_DIR"
-	ls -l "${PUBLISH_DIR}/${file}"
+  if [ ! -f "$file" ]; then
+    echo "Skipping $file"
+    continue
+  fi
+  cmd="cp \"$file\" \"$PUBLISH_DIR\""
+  echo "> $cmd"
+  eval "$cmd"
+  ls -lh "${PUBLISH_DIR}/$(basename ${file})"
 done
